version: "3.7"
services:
  web:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - 2memtask
  db:
    image: "postgres:13.4-alpine"
    container_name: db
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: postgres
    networks:
      - 2memtask
networks:
  2memtask:
    driver: bridge
volumes:
  pgdata: